baseURL = "https://osada.blog"
languageCode = "en-gb"
defaultContentLanguage = "en"
author = "Osada Lakmal Paranaliyanage"
title = "Osada Blog – Thoughts on Software Engineering, Programming, Systems, and Life"

[pagination]
pagerSize = 10

enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[services]
[services.googleAnalytics]
id = 'G-0KDQ9KLJCX'

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
# uBlogger theme version
version = "2.0.X"

# Use homepage.md instead of a list of posts
homepage = false

# Add pagetitle to homepage <title> tag
# pagetitle = "All about static site generation"

# Activate to show authors on pages if available
#listAuthor = true

# Add math typesetting with KaTeX (Global with this Param)
math = true

# Optional 80x80 avatar image.
avatar = "https://osada.blog/profile.jpg"

# Optional favicons for website
favicon = "/img/favicon.ico"

# Add list of sections that should show up on the homepage
mainSections = ["posts"]

description = "Curiously recurring thoughts on software engineering, systems, leadership, and life."
keywords = [
	"programming",
	"systems",
	"osada",
	"software engineering",
	"fatherhood",
]


hidden = [""]

[params.opengraph.twitter]
site = "osadaparanaliyanage"
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

# Add list of Sections/Types that should no be considered by RSS
#nofeedSections = ["post"]

# Deactivate Taxonomies for specific page types
#disableTaxoTypes = [""]

# Custom CSS applied to default styles. (Path could be "static/css/")
#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/osadalakmal"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

[[params.Social.Twitter]]
creator = "osada_lakmal"

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration
noClasses = false

[markup.goldmark.renderer]
hardWraps = true
unSafe = true

[related]
includeNewer = false
threshold = 80
toLower = false
[[related.indices]]
name = 'keywords'
weight = 100
[[related.indices]]
name = 'date'
weight = 10

[params.sidebar]
emoji = "🧑‍💻"
subtitle = "Musings about coding, systems, fatherhood and everything in between."

[params.sidebar.avatar]
enabled = true
local = false
src = "https://osada.blog/profile.jpg"

[module]
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
